// Explicit exports for better auto-completion and type suggestions
export { client, db } from "./connection";
export {
  users,
  sessions,
  accounts,
  verifications,
  stores,
  storeUsers,
  products,
  productImages,
  twoFactor,
  externalStoreMappings,
  storeFolders,
  headBand,
  notifications,
  type Store,
  type NewStore,
  type User,
  type NewUser,
  type Session,
  type NewSession,
  type ExternalStoreMappings,
  type NewExternalStoreMappings,
  type StoreFolder,
  type NewStoreFolder,
  type HeadBand,
  type NewHeadBand,
} from "./schema";
