// Explicit exports for better auto-completion and type suggestions
export { client, db } from './connection';
export {
  users,
  sessions,
  accounts,
  verifications,
  stores,
  storeUsers,
  categories,
  products,
  productImages,
  userInventoryPreferences,
  twoFactor,
  externalStoreMappings,
  storeFolders,
  headBand,
  notifications,
  carts,
  cartItems,
  type Store,
  type NewStore,
  type User,
  type NewUser,
  type Session,
  type NewSession,
  type ExternalStoreMappings,
  type NewExternalStoreMappings,
  type StoreFolder,
  type NewStoreFolder,
  type HeadBand,
  type NewHeadBand,
  type Cart,
  type NewCart,
  type CartItem,
  type NewCartItem
} from './schema';
